set(BOBBY_APP_NAME bobbyquad_feedc0de)
set(BOBBY_DEFAULT_USERNAME feedc0de)

set(BOBBYCAR_BUILDFLAGS
# Pins
#    -DFEATURE_JOYSTICK
#    -DPINS_RX1=4
#    -DPINS_TX1=5
#    -DPINS_RX2=22
#    -DPINS_TX2=23
    -DPINS_MOSFET0=4
    -DPINS_MOSFET1=5
    -DPINS_MOSFET2=25
#    -DPINS_GAMETRAKX=34
#    -DPINS_GAMETRAKY=39
#    -DPINS_GAMETRAKDIST=36
    -DPINS_LEDBACKLIGHT=23
    -DPINS_LEDSTRIP=26

# Config flags
    -DFEATURE_ADC_IN
    -DFEATURE_CAN
#    -DFEATURE_SERIAL
    -DFEATURE_MOSFETS
#    -DFEATURE_BLUETOOTH
#    -DFEATURE_BMS
#    -DFEATURE_GAMETRAK
    -DFEATURE_POWERSUPPLY
    -DFEATURE_LEDBACKLIGHT

    -DLEDBACKLIGHT_INVERTED
#    -DLEDSTRIP_WRONG_DIRECTION
#    -DHEAP_LRGST_CRASH_TEXT_FIX

# Default values
    -DDEFAULT_SWAPSCREENBYTES=false
    -DDEFAULT_INVERTFRONTLEFT=false
    -DDEFAULT_INVERTFRONTRIGHT=true
    -DDEFAULT_INVERTBACKLEFT=false
    -DDEFAULT_INVERTBACKRIGHT=true
    -DDEFAULT_WHEELDIAMETER=255
    -DDEFAULT_IMOTMAX=40
    -DDEFAULT_IDCMAX=42
    -DDEFAULT_NMOTMAX=2000
    -DDEFAULT_FIELDWEAKMAX=17
    -DDEFAULT_FIELDADVMAX=40

# DPAD
    -DFEATURE_DPAD_5WIRESW_2OUT
    -DPINS_DPAD_5WIRESW_OUT1=18
    -DPINS_DPAD_5WIRESW_OUT2=19
    -DPINS_DPAD_5WIRESW_IN1=27
    -DPINS_DPAD_5WIRESW_IN2=32
    -DPINS_DPAD_5WIRESW_IN3=33
#    -DFEATURE_DPAD_6WIRESW
#    -DPINS_DPAD_6WIRESW_OUT=4
#    -DPINS_DPAD_6WIRESW_IN1=5
#    -DPINS_DPAD_6WIRESW_IN2=27
#    -DPINS_DPAD_6WIRESW_IN3=18
#    -DPINS_DPAD_6WIRESW_IN4=19
#    -DPINS_DPAD_6WIRESW_IN5=26
#    -DFEATURE_GSCHISSENE_DIODE
#    -DDPAD_BOARDCOMPUTER_V2
)
